### ISSUE TITLE
is this possible to do without webpack?

### ISSUE THREAD

**Issue by jess** [pascallaliberte/vue-turbolinks-demo#1]
I have an app that doesn't use webpack (yet) but want to know how/if possible if we can implement same strategy with regular js, turbolinks and vuejs (manualy included) - thanks for any help!

**Comment by pascallaliberte** [comment]
HI Jess,

I think you should be able to do it.

The trick relies on two pieces:

1) [This mixin](https://github.com/pascallaliberte/vue-turbolinks-demo/blob/master/_assets/vue/mixins/vue-turbolinks.js), which is [used in app.js on line 6](https://github.com/pascallaliberte/vue-turbolinks-demo/blob/master/_assets/app.js#L6) and which gets propagated throughout all the Vue objects.
2) The work done through the [event listeners on line 38 of app.js](https://github.com/pascallaliberte/vue-turbolinks-demo/blob/master/_assets/app.js#L38)

Without webpack, you can still define your components all in one js file (e.g. app.js) and you can define the mixin in that one file itself too. And you can hook into those event listeners the same. You've got all the same options. In the mixin file, there's an import statement for Vue, but the Vue class should already be in the global (window) scope. You should be all set.

Hope this helps.

I'll be closing the issue next week.

**Comment by jess** [comment]
@pascallaliberte thanks so much. I'll give this a try and report back for anyone looking here in the future.
